# Generated by Django 5.1.7 on 2025-03-19 09:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0002_car'),
    ]

    operations = [
        migrations.RenameField(
            model_name='car',
            old_name='brend',
            new_name='brand',
        ),
    ]
